### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Domosed-gamin** [agustinruatta/racer#1]
Hi. Cool little game. I remember when I was child, I had brick game. Good implementation. I like how you make cars crash. Only small mistakes. When game ends, cursor disappears. And no English.

**Comment by agustinruatta** [comment]
Hi @Domosed-gamin! Thanks for the feedback! This is a very old project when I was in the University (about 7 years ago), so that's why there is no English in the code neither in the app (and, to be honest, the code is crap. There are big mistakes in it). 

The aim was to recreate brick game. So, I hope you had a good time remembering these old times!
